In [1]:
import cv2, os, time
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
class GetData:
    @staticmethod
    def get_images(folder_path):
        data_folder= os.path.join(os.curdir, folder_path)
        data_set = [os.path.join(data_folder,file) for file in os.listdir(data_folder) if os.path.isfile(os.path.join(data_folder,file))]
        images = [cv2.imread(x , cv2.IMREAD_GRAYSCALE) for x in data_set]
        return images

    @staticmethod
    def get_video_cuts(video_path, output_path):
        vidcap = cv2.VideoCapture(video_path)
        success,image = vidcap.read()
        count = 0
        success = True
        while success and count < 100:
            cv2.imwrite(output_path + "/frame%d.jpg" % count, image) 
            success,image = vidcap.read()
            count += 1
        return DataHandler.get_images(output_path)    

In [8]:
star = cv2.xfeatures2d.StarDetector_create()
detector = cv2.xfeatures2d.FREAK_create()
model = RandomForestClassifier()

images_good = GetData.get_images('train_true')
images_other = GetData.get_images('train_false')

X = []
Y = []

for i in images_good:
    kps=star.detect(i,None)
    kps, desc = detector.compute(i, kps)
    try:
        if len(desc) > 30:
            X.append(desc[:30])
            Y.append(1)
        else:
            print("Not pass")
    except Exception:
        print("Oops...Something goes wrong!")

for i in images_other:
    kps=star.detect(i,None)
    kps, desc = detector.compute(i, kps)
    try:
        if len(desc) > 30:
            X.append(desc[:30])
            Y.append(0)
        else:
            print("Not pass")
    except Exception:
        print("Oops...Something goes wrong!")



X = np.array(X)
X = X.reshape(X.shape[0], -1)
Y = np.array(Y)

model.fit(X, Y)


Not pass
Not pass
Not pass
Not pass
Not pass
Not pass


C:\Users\Danul\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [9]:
model.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0])

In [10]:
images_good = GetData.get_images('test_true')
images_other = GetData.get_images('test_false')

X = []
X1= []


for i in images_good:
    kps=star.detect(i,None)
    kps, desc = detector.compute(i, kps)
    try:
        if len(desc) > 30:
            X.append(desc[:30])
        else:
            print("Not pass")
    except Exception:
        print("Oops...Something goes wrong!")

for i in images_other:
    kps=star.detect(i,None)
    kps, desc = detector.compute(i, kps)
    try:
        if len(desc) > 30:
            X1.append(desc[:30])
        else:
            print("Not pass")
    except Exception:
        print("Oops...Something goes wrong!")

X = np.array(X)
X = X.reshape(X.shape[0], -1)

X1 = np.array(X1)
X1 = X1.reshape(X1.shape[0], -1)



Not pass
Not pass
Not pass
Not pass
Not pass
Not pass
Not pass
Not pass
Not pass


In [11]:
start = time.time()
x_predict_true = model.predict(X) # test_true
x_predict_false = model.predict(X1) # test_false
time_spend = time.time() - start # время

print(time_spend)
print("Помилок першого роду = ", int(np.sum(x_predict_false)))
print("Помилок другого роду = ", int(x_predict_true.size - np.sum(x_predict_true)))
print("Всего распознано = ", x_predict_true.size + x_predict_false.size, "из", 179)

0.003000020980834961
Помилок першого роду =  41
Помилок другого роду =  41
Всего распознано =  170 из 179


In [12]:
x_predict_false

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0])

In [13]:
x_predict_true

array([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])